#[path = "../../blog-api/resources/comments.controller.rs"]
pub mod blog_comments;
#[path = "../../blog-api/resources/posts.controller.rs"]
pub mod blog_posts;
#[path = "../../enterprise-saas/resources/customers.controller.rs"]
pub mod enterprise_customers;
#[path = "../../enterprise-saas/resources/invoices.controller.rs"]
pub mod enterprise_invoices;
#[path = "../../enterprise-saas/resources/payments.controller.rs"]
pub mod enterprise_payments;
#[path = "../../incident-platform/resources/alerts.controller.rs"]
pub mod incident_alerts;
#[path = "../../incident-platform/resources/incidents.controller.rs"]
pub mod incident_incidents;
#[path = "../../incident-platform/resources/services.controller.rs"]
pub mod incident_services;
#[path = "../../recipes/rate_limited_public/resources/contact_requests.controller.rs"]
pub mod rate_limited_contact_requests;
#[path = "../../multi-service/services/orders-api/resources/orders.controller.rs"]
pub mod service_orders;
#[path = "../../multi-service/services/users-api/resources/users.controller.rs"]
pub mod service_users;
#[path = "../../multi-tenant/resources/organizations.controller.rs"]
pub mod tenant_organizations;
#[path = "../../multi-tenant/resources/projects.controller.rs"]
pub mod tenant_projects;
#[path = "../../multi-tenant/resources/tasks.controller.rs"]
pub mod tenant_tasks;
