use std::fs;
use std::process::Command;

/// Build release binary, optionally generating a Docker image.
pub fn run(docker: bool) -> i32 {
    if docker {
        return build_docker();
    }

    println!("Building release binary...");
    let status = Command::new("cargo").args(["build", "--release"]).status();

    match status {
        Ok(s) if s.success() => {
            println!("Release binary built successfully");
            0
        }
        Ok(s) => s.code().unwrap_or(1),
        Err(e) => {
            eprintln!("Failed to run cargo build: {e}");
            1
        }
    }
}

fn build_docker() -> i32 {
    let config = match super::load_config() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("Error: {e}");
            return 1;
        }
    };

    let app_name = &config.project;

    let dockerfile = format!(
        r#"# Generated by: shaperail build --docker
FROM rust:1.75-slim AS builder
RUN apt-get update && apt-get install -y pkg-config libssl-dev libpq-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim AS runtime
RUN apt-get update && apt-get install -y ca-certificates libpq5 \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -r -s /bin/false appuser
COPY --from=builder /app/target/release/{app_name} /usr/local/bin/{app_name}
USER appuser
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=3s \
    CMD curl -f http://localhost:3000/health || exit 1
CMD ["{app_name}"]
"#
    );

    if let Err(e) = fs::write("Dockerfile", &dockerfile) {
        eprintln!("Error writing Dockerfile: {e}");
        return 1;
    }

    println!("Generated Dockerfile");
    println!("Building Docker image '{app_name}'...");

    let status = Command::new("docker")
        .args(["build", "-t", app_name, "."])
        .status();

    match status {
        Ok(s) if s.success() => {
            println!("Docker image '{app_name}' built successfully");
            0
        }
        Ok(s) => {
            eprintln!("Docker build failed");
            s.code().unwrap_or(1)
        }
        Err(e) => {
            eprintln!("Failed to run docker build: {e}");
            eprintln!("Is Docker installed and running?");
            1
        }
    }
}
