use std::fs;
use std::process::Command;

const RUST_TOOLCHAIN_VERSION: &str = "1.85";
const MUSL_TARGET: &str = "x86_64-unknown-linux-musl";

/// Build release binary, optionally generating a Docker image.
pub fn run(docker: bool) -> i32 {
    if docker {
        return build_docker();
    }

    println!("Building release binary...");
    let status = Command::new("cargo").args(["build", "--release"]).status();

    match status {
        Ok(s) if s.success() => {
            println!("Release binary built successfully");
            0
        }
        Ok(s) => s.code().unwrap_or(1),
        Err(e) => {
            eprintln!("Failed to run cargo build: {e}");
            1
        }
    }
}

fn build_docker() -> i32 {
    let config = match super::load_config() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("Error: {e}");
            return 1;
        }
    };

    let app_name = &config.project;

    let dockerfile = render_dockerfile(app_name);

    if let Err(e) = fs::write("Dockerfile", &dockerfile) {
        eprintln!("Error writing Dockerfile: {e}");
        return 1;
    }

    println!("Generated Dockerfile");
    println!("Building Docker image '{app_name}'...");

    let status = Command::new("docker")
        .args(["build", "-t", app_name, "."])
        .status();

    match status {
        Ok(s) if s.success() => {
            println!("Docker image '{app_name}' built successfully");
            0
        }
        Ok(s) => {
            eprintln!("Docker build failed");
            s.code().unwrap_or(1)
        }
        Err(e) => {
            eprintln!("Failed to run docker build: {e}");
            eprintln!("Is Docker installed and running?");
            1
        }
    }
}

fn render_dockerfile(app_name: &str) -> String {
    format!(
        r#"# Generated by: shaperail build --docker
FROM rust:{RUST_TOOLCHAIN_VERSION}-slim AS builder
RUN apt-get update && apt-get install -y musl-tools pkg-config ca-certificates \
    && rm -rf /var/lib/apt/lists/*
RUN rustup target add {MUSL_TARGET}
WORKDIR /app
COPY . .
RUN cargo build --release --target {MUSL_TARGET}

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /app/target/{MUSL_TARGET}/release/{app_name} /{app_name}
USER 10001:10001
EXPOSE 3000
ENTRYPOINT ["/{app_name}"]
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_dockerfile_targets_scratch_runtime() {
        let dockerfile = render_dockerfile("my-app");

        assert!(dockerfile.contains("FROM scratch"));
        assert!(dockerfile.contains("x86_64-unknown-linux-musl"));
        assert!(dockerfile.contains("ENTRYPOINT [\"/my-app\"]"));
        assert!(!dockerfile.contains("debian:bookworm-slim"));
    }
}
