use std::fs;
use std::path::Path;

use super::load_all_resources;

/// Run codegen for all resource files, writing output to generated/.
pub fn run() -> i32 {
    let resources = match load_all_resources() {
        Ok(r) => r,
        Err(e) => {
            eprintln!("Error: {e}");
            return 1;
        }
    };

    let generated_dir = Path::new("generated");
    if let Err(e) = fs::create_dir_all(generated_dir) {
        eprintln!("Error creating generated/ directory: {e}");
        return 1;
    }

    for resource in &resources {
        let file_name = format!("{}.rs", resource.resource);
        let output_path = generated_dir.join(&file_name);

        let code = generate_module(resource);

        if let Err(e) = fs::write(&output_path, &code) {
            eprintln!("Error writing {}: {e}", output_path.display());
            return 1;
        }

        println!("Generated {}", output_path.display());
    }

    // Write mod.rs
    let mod_contents: String = resources
        .iter()
        .map(|r| format!("pub mod {};", r.resource))
        .collect::<Vec<_>>()
        .join("\n");

    if let Err(e) = fs::write(generated_dir.join("mod.rs"), format!("{mod_contents}\n")) {
        eprintln!("Error writing generated/mod.rs: {e}");
        return 1;
    }

    println!(
        "Generated {} resource module(s) in generated/",
        resources.len()
    );
    0
}

/// Generate a minimal Rust module for a resource definition.
fn generate_module(resource: &shaperail_core::ResourceDefinition) -> String {
    let name = &resource.resource;
    let struct_name = to_pascal_case(name);

    let mut fields = String::new();
    for (field_name, schema) in &resource.schema {
        let rust_type =
            schema
                .field_type
                .to_rust_type(schema.required, schema.nullable, schema.generated);
        fields.push_str(&format!("    pub {field_name}: {rust_type},\n"));
    }

    format!(
        r#"//! Generated module for the `{name}` resource.
//! DO NOT EDIT — this file is auto-generated by `shaperail generate`.

use serde::{{Deserialize, Serialize}};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct {struct_name} {{
{fields}}}
"#
    )
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => {
                    let upper: String = c.to_uppercase().collect();
                    upper + &chars.as_str().to_lowercase()
                }
            }
        })
        .collect()
}
